=== Jdothager/Star-Trek-Script-Programmatics/processed/_schema.json
{
   "$schema": "http://json-schema.org/draft-07/schema#",
   "title": "Episode",
   "description": "An episode of Star Trek",
   "type": "object",
   "required": [
      "title",
      "stardate",
      "airdate",
      "schedule",
      "scenes"
   ],
   "properties": {
      "title": {
         "description": "The title of the episode",
         "type": "string"
      },
      "stardate": {
         "description": "Stardate of the episode",
         "type": "string"
      },
      "airdate": {
         "description": "Day of airing of the episode in UTC epoch timestamp",
         "type": "integer"
      },
      "schedule": {
         "description": "Information about the episode's temporal place in the series",
         "type": "object",
         "required": [
            "season",
            "episode",
            "number"
         ],
         "properties": {
            "season": {
               "type": "number"
            },
            "episode": {
               "type": "number"
            },
            "number": {
               "type": "number"
            }
         }
      },
      "scenes": {
         "description": "List of scenes within the episode",
         "type": "array",
         "items": {
            "type": "object",
            "required": [
               "dialogue",
               "location"
            ],
            "properties": {
               "dialogue": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "required": [
                        "character",
                        "line"
                     ],
                     "properties": {
                        "character": {
                           "type": "string",
                           "description": "The character speaking"
                        },
                        "line": {
                           "type": "string",
                           "description": "The line of speech spoken by the character"
                        },
                        "modifier": {
                           "type": "string",
                           "enum": ["voiceover", "screen"],
                           "description": "A modifier of the speech."
                        }
                     }
                  }
               },
               "location": {
                  "type": "string",
                  "description": "The location of the scene"
               }
            }
         }
      }
   }
}

=== Jdothager/Star-Trek-Script-Programmatics/processed/tng/s04e11.json
{
  "airdate": 663224400,
  "scenes": [
    {
      "dialogue": [
        {
          "character": "unknown",
          "line": "Second Officer's personal Log, Stardate 44390.1. Record entry for transmission to Commander Bruce Maddox, Cybernetics Division, Daystrom Institute. Dear Commander Maddox,"
        }
      ],
      "location": "unknown"
    },
    {
      "dialogue": [
        {
          "character": "DATA",
          "line": "In reference to your most recent letter, I agree that your study lacks sufficient primary source information on my programming and operation. Therefore, in response to your request, this correspondence will include a complete record of my activities during a normal day, with particular emphasis on my perceptions of friendship.",
          "modifier": "voiceover"
        },
        {
          "character": "DATA",
          "line": "Commander Riker, you are fifteen minutes early."
        },
        {
          "character": "RIKER",
          "line": "Well, it's a very special day. I thought the father of the bride would enjoy being relieved early on the wedding day."
        },
        {
          "character": "DATA",
          "line": "Thank you, sir."
        },
        {
          "character": "RIKER",
          "line": "Nervous?"
        },
        {
          "character": "DATA",
          "line": "I cannot become nervous, sir. However, I do sense a certain anticipation regarding my role in the wedding."
        },
        {
          "character": "RIKER",
          "line": "Anything to report?"
        },
        {
          "character": "DATA",
          "line": "All systems normal, sir. Sickbay reports that Lieutenant Juarez went into labor at zero four hundred hours. We remain at station awaiting the arrival of Starship Zhukov and guest quarters have been prepared for Ambassador T'Pel."
        },
        {
          "character": "RIKER",
          "line": "Very well. I have the Bridge."
        },
        {
          "character": "DATA",
          "line": "Aye, sir."
        },
        {
          "character": "RIKER",
          "line": "Begin day watch."
        },
        {
          "character": "DATA",
          "line": "Initially, Commander Maddox, I found it difficult to maintain friendships, since human emotions are often puzzling to me.",
          "modifier": "voiceover"
        }
      ],
      "location": "Bridge"
    },
    {
      "dialogue": [
        {
          "character": "DATA",
          "line": "Eventually, I developed a program enabling me to predict human emotional responses to specific actions.",
          "modifier": "voiceover"
        }
      ],
      "location": "Corridor"
    },
    {
      "dialogue": [
        {
          "character": "KEIKO",
          "line": "Come in."
        },
        {
          "character": "DATA",
          "line": "It is time for the wedding rehearsal."
        },
        {
          "character": "KEIKO",
          "line": "I know. Data, I've decided not to go through with it."
        },
        {
          "character": "DATA",
          "line": "You do not wish to rehearse?"
        },
        {
          "character": "KEIKO",
          "line": "No, I'm calling off the wedding."
        },
        {
          "character": "DATA",
          "line": "May I ask why?"
        },
        {
          "character": "KEIKO",
          "line": "It's just the right thing to do."
        },
        {
          "character": "DATA",
          "line": "Have your feelings for Chief O'Brien changed?"
        },
        {
          "character": "KEIKO",
          "line": "I'm supposed to be getting married, Data. I should be happy, but I'm not. I just feel this weight pressing down on me."
        },
        {
          "character": "DATA",
          "line": "Will canceling the wedding make you happy?"
        },
        {
          "character": "KEIKO",
          "line": "Yes. He'll probably be just as relieved as I am. Data, you introduced us to each other. You mean a lot to both of us. I would really appreciate it if you would tell Miles for me."
        },
        {
          "character": "DATA",
          "line": "If you wish."
        }
      ],
      "location": "Keiko's quarters"
    },
    {
      "dialogue": [
        {
          "character": "DATA",
          "line": "My friend Chief O'Brien often says that above all else, he wants to make Keiko happy. Since canceling the wedding will make her happy, I must conclude the Chief will be pleased at her decision.",
          "modifier": "voiceover"
        },
        {
          "character": "DATA",
          "line": "I have good news."
        },
        {
          "character": "O'BRIEN",
          "line": "Oh?"
        },
        {
          "character": "DATA",
          "line": "Keiko has made a decision designed to increase her happiness. She has canceled the wedding."
        },
        {
          "character": "O'BRIEN",
          "line": "She what? Canceled the wedding? Today? Without even a word? Of all the childish, selfish, irresponsible things to do!"
        },
        {
          "character": "LAFORGE",
          "line": "Next time, maybe I should break the good news."
        },
        {
          "character": "DATA",
          "line": "Commander Maddox, it would appear that my program designed to predict the emotional responses needs adjustment. Second Officers personal log, supplemental. This is the one thousand five hundred fiftieth day since the Enterprise was commissioned. Besides the arrival of Ambassador T'Pel, other events occurring today include four birthdays, two personnel transfers, a celebration of the Hindu Festival of Lights, two chess tournaments, one secondary school play, and four promotions. Overall, an ordinary day.",
          "modifier": "voiceover"
        }
      ],
      "location": "Ten Forward"
    },
    {
      "dialogue": [
        {
          "character": "TECHNICIAN",
          "line": "The Zhukov is ready for transport, sir."
        },
        {
          "character": "DATA",
          "line": "Energize."
        },
        {
          "character": "DATA",
          "line": "Welcome aboard the Enterprise, Ambassador."
        },
        {
          "character": "T'PEL",
          "line": "I would meet with your Captain."
        }
      ],
      "location": "Transporter room"
    },
    {
      "dialogue": [
        {
          "character": "DATA",
          "line": "Sine I am not affected by emotional considerations, I am closer to being Vulcan than human. However, while their devotion to logic does have a certain appeal, I find their stark philosophy to be somewhat limited.",
          "modifier": "voiceover"
        }
      ],
      "location": "Turbolift"
    },
    {
      "dialogue": [
        {
          "character": "PICARD",
          "line": "Come. Ambassador T'Pel."
        },
        {
          "character": "T'PEL",
          "line": "I come to serve."
        },
        {
          "character": "PICARD",
          "line": "Your service honors us. This is my first officer, Commander William Riker."
        },
        {
          "character": "T'PEL",
          "line": "Leave us, please."
        }
      ],
      "location": "Ready room"
    },
    {
      "dialogue": [
        {
          "character": "RIKER",
          "line": "Charming woman."
        },
        {
          "character": "DATA",
          "line": "The tone of Commander Riker's voice makes me suspect that he is not serious about finding Ambassador T'Pel charming. My experience suggests that in fact he may mean the exact opposite of what he says. irony is a form of expression I have not yet been able to master.",
          "modifier": "voiceover"
        }
      ],
      "location": "Bridge"
    },
    {
      "dialogue": [
        {
          "character": "V'SAL",
          "line": "You don't need a haircut. You were just in here last week."
        },
        {
          "character": "LAFORGE",
          "line": "Hey, if you'd done it right the first time I wouldn't be back here so soon."
        },
        {
          "character": "V'SAL",
          "line": "I know you want to look beautiful, but I'm just a barber, not a miracle worker."
        },
        {
          "character": "LAFORGE",
          "line": "Just try to keep my ears on straight today, all right?"
        },
        {
          "character": "DATA",
          "line": "Friendly insults and jibes, another form of human speech that I am attempting to master, in this case with the help of Commander Geordi La Forge.",
          "modifier": "voiceover"
        },
        {
          "character": "LAFORGE",
          "line": "Hi Data."
        },
        {
          "character": "DATA",
          "line": "I consider Geordi to be my best friend.",
          "modifier": "voiceover"
        },
        {
          "character": "LAFORGE",
          "line": "Here for a trim?"
        },
        {
          "character": "DATA",
          "line": "My hair does not require trimming, you lunkhead."
        },
        {
          "character": "LAFORGE",
          "line": "What?"
        },
        {
          "character": "DATA",
          "line": "My hair does not require trimming"
        },
        {
          "character": "LAFORGE",
          "line": "Lunkhead?"
        },
        {
          "character": "DATA",
          "line": "I am experimenting with friendly jibes and insults. It was not meant as a serious disparagement."
        },
        {
          "character": "LAFORGE",
          "line": "Well, just don't try it on the Captain."
        },
        {
          "character": "DATA",
          "line": "No. Geordi, I am still confused by Chief O'Brien's reaction this morning."
        },
        {
          "character": "LAFORGE",
